- block:
    - name: create temporary directory
      tempfile: {state: directory, suffix: .nginx}
      register: tmp_dir
    
    - name: transport nginx and keepalive binary package
      unarchive:
        src: "{{ software_dir }}/ha.tar.gz"
        dest: "{{ tmp_dir.path }}"
    
    - name: deploy keepalive
      yum:
        name: "{{ tmp_dir.path }}/{{ item }}"
        state: present
      loop:
        - "net-snmp-libs-5.7.2-43.el7.x86_64.rpm"
        - "net-snmp-agent-libs-5.7.2-43.el7.x86_64.rpm"
        - "keepalived-1.3.5-16.el7.x86_64.rpm"
    
    - name: deploy nginx to achieve LB
      yum:
        name: "{{ tmp_dir.path }}/nginx-1.16.1-1.el7.ngx.x86_64.rpm"
        state: present
    
    - name: transport nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    
    - name: transport keepalive configuration file
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
    
    - name: transport nginx health check script
      copy:
        src: check_nginx.sh
        dest: /etc/keepalived/
        mode: u+x
    
    - name: launch service
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      loop:
        - nginx
        - keepalived
