- block:
    - name: enable ipvs module for kube-proxy
      copy:
        src: ipvs.modules
        dest: /etc/sysconfig/modules/
        mode: 755
        backup: yes

    - name: apply module of ipvs
      shell: "bash /etc/sysconfig/modules/ipvs.modules"
      changed_when: false

    - name: verify ipvs module
      shell: "lsmod | grep -e ip_vs -e nf_conntrack"
      register: mod_output

    - name: show verification
      debug: {msg: "ipvs verification is {{ mod_output.rc }}"}

  rescue:
    - when: mod_output.rc != 0
      debug: {msg: "verification status is {{ mod_output.failed }}"}
