- block:
    - name: create directory for journal
      file: {path: "/var/log/journal", state: directory}

    - name: create directory for journald.conf.d
      file: {path: "/etc/systemd/journald.conf.d", state: directory}

    - name: transport configuration file
      copy:
        src: 99-prophet.conf
        dest: /etc/systemd/journald.conf.d/
        backup: yes

    - name: restart journald service
      systemd:
        name: systemd-journald
        state: restarted
      register: journald_output

  rescue:
    - when: journald_output.rc != 0
      debug: {msg: 'restarted journald service got abnormal state, Please check it'}
